### ISSUE TITLE
Future of this project

### ISSUE THREAD

**Issue by Gilgalidd** [efenian/phpipamsdk#1]
Hello,

I've discover your repo because I search an alternative to the phpIpam-agent to be supported under windows server ( php version cannot due to the non-support of pcntl).

So, what do you plan for you project? As I can see you begin to write some function to scan network and much more.

Bye.

**Comment by efenian** [comment]
It's just a python client for the phpipam REST API that I have been working on:

https://phpipam.net/api/api_documentation/

It's not meant as a scan-agent for phpipam, like what exists here: https://github.com/phpipam/phpipam-agent
